// export const FETCH_TRANSACTIONS_REQUEST = "FETCH_TRANSACTIONS_REQUEST";
// export const FETCH_TRANSACTIONS_SUCCESS = "FETCH_TRANSACTIONS_SUCCESS";
// export const FETCH_TRANSACTIONS_ERROR = "FETCH_TRANSACTIONS_ERROR";

// export const FETCH_TRANSACTIONS_INCOMING_REQUEST =
//   "FETCH_TRANSACTIONS_INCOMING_REQUEST";
// export const FETCH_TRANSACTIONS_INCOMING_SUCCESS =
//   "FETCH_TRANSACTIONS_INCOMING_SUCCESS";
// export const FETCH_TRANSACTIONS_INCOMING_ERROR =
//   "FETCH_TRANSACTIONS_INCOMING_ERROR";
